version: "3.2"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./:/usr/src/app
    environment:
      - JWT_SECRET=secret
      - MONGO_URI=mongodb://mongo:27017/test
      - OMDb_API_KEY=12379d38
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
